import type { Config } from '@stencil/core';

// Framework-neutral build only. Angular/Vue proxies are generated by adapter
// packages when a real consumer needs them (ADR-0001, Decision 2).
export const config: Config = {
  namespace: 'tjprimitives',
  outputTargets: [
    {
      type: 'dist-custom-elements',
      dir: 'dist/components',
      customElementsExportBehavior: 'bundle',
      externalRuntime: false,
      generateTypeDeclarations: true,
    },
  ],
};
