/**
 * Flutter (Dart) token formats (Style Dictionary `format`s).
 *
 * Generates a Dart 3 constants class per brand plus per-theme color maps. The
 * value policy lives in `../values.js`; here we only render it as idiomatic
 * Dart. Emits `dart:ui` (not material) so the artifact stays usable in any
 * Flutter/`dart:ui` context — consumers compose a `ThemeExtension` from these
 * constants if they need `ThemeData` theming.
 */
import type { File, Format, FormatFnArguments } from 'style-dictionary/types';
import {
  buildTree,
  dartDouble,
  flattenTree,
  hexByte,
  type Normalized,
} from '../values.js';

const HEADER = `// AUTO-GENERATED by @thijulio/core — do not edit.
// Flutter token artifact. Source of truth: the brand's src/tokens JSON.
// Value policy:
//   - px / rem -> logical pixels (double; rem assumes a 16px root)
//   - s / ms   -> milliseconds (int)
//   - em       -> bare letter-spacing coefficient (double)
//   - cubic-bezier(...) -> CubicBezier
//   - clamp(min, vw, max) -> min (mobile bound)
//   - colors   -> Color (0xFFRRGGBB, or fromRGBO when translucent)
//   - font stacks / shadows / compound radius -> opaque String (web-only)
//
// Theme overlays are color-only in this repo, so theme maps are typed
// Map<String, Color>.`;

const CUBIC_BEZIER = `class CubicBezier {
  final double x1;
  final double y1;
  final double x2;
  final double y2;
  const CubicBezier(this.x1, this.y1, this.x2, this.y2);
}`;

/** The brand class-name fragment, e.g. "Biome" → `BiomeTokens`. */
function brandName(file: File): string {
  const opts = (file.options ?? {}) as Record<string, unknown>;
  const raw = String(opts.displayName ?? 'Brand');
  const cleaned = raw.replace(/[^A-Za-z0-9_]/g, '');
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

/** The Dart type of a normalized leaf. */
function dartType(value: Normalized): string {
  switch (value.kind) {
    case 'easing':
      return 'CubicBezier';
    case 'color':
      return 'Color';
    case 'duration':
    case 'integer':
      return 'int';
    case 'dimension':
    case 'decimal':
      return 'double';
    case 'opaque':
      return 'String';
  }
}

function escapeDart(s: string): string {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\$/g, '\\$')
    .replace(/\n/g, '\\n');
}

/** A Dart literal (const-evaluable) for a normalized leaf. */
function dartLiteral(value: Normalized): string {
  switch (value.kind) {
    case 'easing':
      return `CubicBezier(${dartDouble(value.x1)}, ${dartDouble(
        value.y1,
      )}, ${dartDouble(value.x2)}, ${dartDouble(value.y2)})`;
    case 'color':
      return value.a >= 1
        ? `Color(0xFF${hexByte(value.r)}${hexByte(value.g)}${hexByte(value.b)})`
        : `Color.fromRGBO(${value.r}, ${value.g}, ${value.b}, ${dartDouble(
            value.a,
          )})`;
    case 'duration':
      return `${value.ms}`;
    case 'integer':
      return `${value.value}`;
    case 'dimension':
    case 'decimal':
      return dartDouble(value.value);
    case 'opaque':
      return `'${escapeDart(value.raw)}'`;
  }
}

/** `abstract final class <Brand>Tokens { static const … }` — base constants. */
const dartBase: Format = {
  name: 'thijulio/dart-base',
  format: ({ dictionary, file }: FormatFnArguments) => {
    const brand = brandName(file);
    const constants = flattenTree(buildTree(dictionary.allTokens))
      .map(
        ({ id, value }) =>
          `  static const ${dartType(value)} ${id} = ${dartLiteral(value)};`,
      )
      .join('\n');
    return `${HEADER}\nimport 'dart:ui' show Color;\n\n${CUBIC_BEZIER}\n\nabstract final class ${brand}Tokens {\n${constants}\n}\n`;
  },
};

/** The Pascal-cased theme class fragment, e.g. `dark` → `Dark`. */
function themeClassName(file: File): string {
  const opts = (file.options ?? {}) as Record<string, unknown>;
  const raw = String(opts.themeName ?? 'Theme');
  const cleaned = raw.replace(/[^A-Za-z0-9_]/g, '');
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

/** `abstract final class <Brand>Theme<Name> { static const Map<String, Color> colors = { … }; }`. */
const dartTheme: Format = {
  name: 'thijulio/dart-theme',
  format: ({ dictionary, file }: FormatFnArguments) => {
    const brand = brandName(file);
    const theme = themeClassName(file);
    const entries = flattenTree(buildTree(dictionary.allTokens));
    // Theme overlays reskin semantic/accent colors in this repo, so values are
    // always Colors. (See the header note — if a theme ever gains non-color
    // tokens, relax this to `Object` and adjust the barrel accordingly.)
    const body = entries
      .map(({ id, value }) => `    '${id}': ${dartLiteral(value)},`)
      .join('\n');
    return `${HEADER}
import 'dart:ui' show Color;
import 'tokens.dart';

abstract final class ${brand}Theme${theme} {
  static const Map<String, Color> colors = {
${body}
  };
}
`;
  },
};

/** All Dart formats, registered once by `platforms.ts`. */
export const dartFormats: Format[] = [dartBase, dartTheme];
