/**
 * React Native token formats (Style Dictionary `format`s).
 *
 * Emits a normalized, nested JS object (plus an exact `.d.ts`) from the same
 * token JSON the web platforms consume. The value policy lives in
 * `../values.js` — these formats only render it.
 *
 * Themes are emitted **per theme** (one SD run each, filtered to the theme's
 * own directory) because multiple themes can override the *same* base token —
 * e.g. Exodus' three accent themes all define `accent-50` — and a single
 * combined run would collapse those collisions.
 *
 * This module is imported by the SD *runner* only (`build-tokens.ts`), never by
 * the pure config factory, so the `style-dictionary` import below is type-only
 * and erased at runtime (keeps `token-config.ts` Jest-friendly).
 */
import type { Format, FormatFnArguments } from 'style-dictionary/types';
import {
  buildTree,
  formatAlpha,
  hexByte,
  isBranch,
  type Normalized,
  type TokenTree,
} from '../values.js';

const HEADER = `/**
 * AUTO-GENERATED by @thijulio/core — do not edit.
 * React Native token artifact. Source of truth: the brand's src/tokens JSON.
 * Value policy:
 *   - px / rem -> logical pixels (rem assumes a 16px root)
 *   - s / ms   -> milliseconds
 *   - em       -> bare letter-spacing coefficient (multiply by font size)
 *   - cubic-bezier(...) -> { x1, y1, x2, y2 }
 *   - clamp(min, vw, max) -> min (mobile bound)
 *   - colors   -> #RRGGBB (rgba(...) when translucent)
 *   - font stacks / shadows / compound radius -> opaque string (web-only)
 */`;

/** Render a normalized value to a JSON-compatible JS literal. */
export function renderJsValue(value: Normalized): unknown {
  switch (value.kind) {
    case 'easing':
      return { x1: value.x1, y1: value.y1, x2: value.x2, y2: value.y2 };
    case 'color':
      return value.a >= 1
        ? `#${hexByte(value.r)}${hexByte(value.g)}${hexByte(value.b)}`
        : `rgba(${value.r}, ${value.g}, ${value.b}, ${formatAlpha(value.a)})`;
    case 'duration':
      return value.ms;
    case 'dimension':
    case 'integer':
    case 'decimal':
      return value.value;
    case 'opaque':
      return value.raw;
  }
}

function treeToJs(tree: TokenTree): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(tree)) {
    out[key] = isBranch(value) ? treeToJs(value) : renderJsValue(value);
  }
  return out;
}

/** The TypeScript type of a normalized leaf. */
export function tsType(value: Normalized): string {
  switch (value.kind) {
    case 'easing':
      return 'Easing';
    case 'color':
    case 'opaque':
      return 'string';
    case 'duration':
    case 'dimension':
    case 'integer':
    case 'decimal':
      return 'number';
  }
}

function treeToDts(tree: TokenTree): string {
  const parts = Object.entries(tree).map(([key, value]) => {
    const k = JSON.stringify(key);
    return `${k}: ${isBranch(value) ? treeToDts(value) : tsType(value)}`;
  });
  return `{ ${parts.join('; ')} }`;
}

/** `export const tokens = { … }` — normalized base tokens. */
const nativeEs6: Format = {
  name: 'thijulio/native-es6',
  format: ({ dictionary }: FormatFnArguments) => {
    const body = JSON.stringify(
      treeToJs(buildTree(dictionary.allTokens)),
      null,
      2,
    );
    return `${HEADER}\nexport const tokens = ${body};\n`;
  },
};

/** Exact TypeScript declaration for the base token tree (plus shared types). */
const nativeDts: Format = {
  name: 'thijulio/native-dts',
  format: ({ dictionary }: FormatFnArguments) => {
    const type = treeToDts(buildTree(dictionary.allTokens));
    return `${HEADER}
export type Easing = { x1: number; y1: number; x2: number; y2: number };
export type TokenValue = number | string | Easing;
export type TokenTree = { [key: string]: TokenTree | TokenValue };

export declare const tokens: ${type};
`;
  },
};

/** `export default { … }` — a single theme overlay (filtered upstream). */
const nativeThemeEs6: Format = {
  name: 'thijulio/native-theme-es6',
  format: ({ dictionary }: FormatFnArguments) => {
    const body = JSON.stringify(
      treeToJs(buildTree(dictionary.allTokens)),
      null,
      2,
    );
    return `${HEADER}\nexport default ${body};\n`;
  },
};

/** All native formats, registered once by `platforms.ts`. */
export const nativeFormats: Format[] = [nativeEs6, nativeDts, nativeThemeEs6];
