import { appendFile, readFile, rm, writeFile } from 'node:fs/promises';
import { basename, join, resolve } from 'node:path';
import StyleDictionary from 'style-dictionary';
import { registerPlatforms } from './platforms.js';
import {
  createBaseConfig,
  createThemeConfig,
  themeTempFile,
  type BuildBrandTokensOptions,
} from './token-config.js';

/** Remove Style Dictionary's leading "Do not edit" header so it appears once per file. */
const stripHeader = (css: string): string =>
  css.replace(/^\/\*\*[\s\S]*?\*\/\s*/, '');

const NATIVE_HEADER = `/**
 * AUTO-GENERATED by @thijulio/core — do not edit.
 */`;

const DART_HEADER = `// AUTO-GENERATED by @thijulio/core — do not edit.`;

/** Theme directory names, e.g. `src/themes/dark` → `dark`. */
function themeNames(themes: BuildBrandTokensOptions['themes']): string[] {
  return (themes ?? []).map((theme) => basename(resolve(theme.source)));
}

function pascal(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_]/g, '');
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

/**
 * Write the React Native aggregators: `themes.js` (barrel over the per-theme
 * files), `index.js` (+ `.d.ts`) with the public `tokens`/`themes`/`resolve`
 * surface.
 */
async function writeNativeBarrels(
  buildPath: string,
  names: string[],
): Promise<void> {
  const dir = join(buildPath, 'native');
  const imports = names
    .map((n) => `import ${n} from './themes/${n}.js';`)
    .join('\n');

  const themesJs = `${NATIVE_HEADER}
${imports}

export const themes = { ${names.join(', ')} };
`;

  const themesDts = `${NATIVE_HEADER}
import type { TokenTree } from './tokens.js';

export declare const themes: Record<string, TokenTree>;
`;

  const indexJs = `${NATIVE_HEADER}
export { tokens } from './tokens.js';
export { themes } from './themes.js';

/** Deep-merge a theme overlay over the base tokens (overlay wins). */
export function resolve(base, overlay) {
  const out = { ...base };
  for (const [key, value] of Object.entries(overlay ?? {})) {
    out[key] =
      value &&
      typeof value === 'object' &&
      !Array.isArray(value) &&
      base &&
      typeof base[key] === 'object' &&
      !Array.isArray(base[key])
        ? resolve(base[key], value)
        : value;
  }
  return out;
}
`;

  const indexDts = `${NATIVE_HEADER}
export { tokens } from './tokens.js';
export { themes } from './themes.js';

export declare function resolve(
  base: Record<string, unknown>,
  overlay: Record<string, unknown>,
): Record<string, unknown>;
`;

  await Promise.all([
    writeFile(join(dir, 'themes.js'), themesJs),
    writeFile(join(dir, 'themes.d.ts'), themesDts),
    writeFile(join(dir, 'index.js'), indexJs),
    writeFile(join(dir, 'index.d.ts'), indexDts),
  ]);
}

/** Write the Dart barrel exposing every theme via `<Brand>Themes.all`. */
async function writeDartBarrel(
  buildPath: string,
  names: string[],
  displayName?: string,
): Promise<void> {
  const brand = pascal(displayName ?? 'Brand');
  const imports = names.map((n) => `import 'theme_${n}.dart';`).join('\n');
  const entries = names
    .map((n) => `'${n}': ${brand}Theme${pascal(n)}.colors`)
    .join(',\n    ');
  // Zero overlays (a light-only brand) must still emit valid Dart — an empty
  // map literal, not a stray comma.
  const mapBody =
    names.length > 0
      ? `{\n    ${entries},\n  }`
      : '<String, Map<String, Color>>{}';
  const dart = `${DART_HEADER}
import 'dart:ui' show Color;
${imports}

abstract final class ${brand}Themes {
  static const Map<String, Map<String, Color>> all = ${mapBody};
}
`;
  await writeFile(join(buildPath, 'dart', 'themes.dart'), dart);
}

/**
 * Build a brand's tokens to disk using the shared config:
 *  - `tokens.css`  the `:root` base block, followed by one block per theme overlay
 *  - `tokens.js` / `tokens.d.ts`  typed objects (base values)
 *  - `native/`     normalized React Native tokens (JS/DTS + per-theme overlays)
 *  - `dart/`       normalized Flutter tokens (constants + per-theme color maps)
 */
export async function buildBrandTokens(
  options: BuildBrandTokensOptions,
): Promise<void> {
  registerPlatforms();
  const { buildPath, themes = [], displayName } = options;
  const names = themeNames(themes);

  // 1. Base: writes tokens.css (:root) + tokens.js/d.ts (web) + native + dart.
  await new StyleDictionary(createBaseConfig(options)).buildAllPlatforms();

  // 2. Each theme overlay → its own CSS temp (appended) + native/dart theme files.
  const tokensCss = join(buildPath, 'tokens.css');
  for (let i = 0; i < themes.length; i++) {
    await new StyleDictionary(
      createThemeConfig(options, themes[i], i),
    ).buildAllPlatforms();

    const tempPath = join(buildPath, themeTempFile(i));
    const overlay = stripHeader(await readFile(tempPath, 'utf-8'));
    await appendFile(tokensCss, `\n${overlay}`);
    await rm(tempPath);
  }

  // 3. Aggregator barrels over the per-theme artifacts.
  await writeNativeBarrels(buildPath, names);
  await writeDartBarrel(buildPath, names, displayName);
}
