/**
 * Self-hosted webfonts — the pure half: the brand manifest types, how a
 * manifest becomes `@font-face` rules, and how those rules are parsed back.
 * No filesystem access here (see build-fonts.ts / verify-fonts.ts), so it is
 * unit-tested directly.
 */

/** Every brand ships exactly these subsets. latin covers PT/FR/EN accents. */
export const FONT_SUBSETS = ['latin', 'latin-ext'] as const;
export type FontSubset = (typeof FONT_SUBSETS)[number];

export type FontStyle = 'normal' | 'italic';

/**
 * Where a family's woff2 files come from. Fontsource names its files
 * `<slug>-<subset>-<axes>-<style>.woff2` (variable) and
 * `<slug>-<subset>-<weight>-<style>.woff2` (static).
 */
export type FontSource =
  /** One file per style per subset covering a weight range (`@fontsource-variable/*`). */
  | {
      kind: 'variable';
      package: string;
      /** `wght` = weight axis only; `opsz` = weight + optical size. */
      axes: 'wght' | 'opsz';
    }
  /** One file per weight per style per subset (`@fontsource/*`). */
  | { kind: 'static'; package: string };

export interface FontFamily {
  /** The CSS `font-family` name the brand's tokens reference. */
  family: string;
  source: FontSource;
  /** Weights each style must render — the brand's font contract. */
  styles: Partial<Record<FontStyle, readonly number[]>>;
}

export type BrandFonts = readonly FontFamily[];

/** One `@font-face` rule to emit, plus the fontsource file that backs it. */
export interface PlannedFontFace {
  family: string;
  style: FontStyle;
  weight: readonly [min: number, max: number];
  subset: FontSubset;
  unicodeRange: string;
  /** Package that ships `file` (resolved as `<package>/files/<file>`). */
  package: string;
  /** woff2 basename — identical in the fontsource package and in dist/fonts/. */
  file: string;
}

/** `@fontsource-variable/hanken-grotesk` → `hanken-grotesk` (fontsource's file prefix). */
export const fontSlug = (pkg: string): string =>
  pkg.slice(pkg.lastIndexOf('/') + 1);

/** Name the OFL licence of `pkg` is shipped under in dist/fonts/. */
export const licenseFileName = (pkg: string): string =>
  `LICENSE-${fontSlug(pkg)}.txt`;

/**
 * Overlapping unicode-ranges (U+0304, U+0308, U+0329 are in both) resolve to
 * the face declared LAST, so latin-ext is emitted first and latin wins —
 * the same order Google Fonts and fontsource use.
 */
const EMIT_ORDER: readonly FontSubset[] = ['latin-ext', 'latin'];

/**
 * Expand a manifest into `@font-face` rules. A variable family gets one face
 * per style per subset spanning exactly the contracted weights (not the file's
 * full axis range: weights outside the contract keep matching the nearest
 * contracted weight, as they did with Google Fonts); a static family gets one
 * face per weight.
 */
export function planFontFaces(
  fonts: BrandFonts,
  unicodeRange: (pkg: string, subset: FontSubset) => string,
): PlannedFontFace[] {
  const faces: PlannedFontFace[] = [];
  for (const { family, source, styles } of fonts) {
    const slug = fontSlug(source.package);
    for (const [style, weights] of Object.entries(styles) as [
      FontStyle,
      readonly number[],
    ][]) {
      if (weights.length === 0)
        throw new Error(`${family} ${style}: no weights listed`);
      const sorted = [...weights].sort((a, b) => a - b);
      for (const subset of EMIT_ORDER) {
        const base = {
          family,
          style,
          subset,
          unicodeRange: unicodeRange(source.package, subset),
          package: source.package,
        };
        if (source.kind === 'variable') {
          faces.push({
            ...base,
            weight: [sorted[0], sorted[sorted.length - 1]],
            file: `${slug}-${subset}-${source.axes}-${style}.woff2`,
          });
        } else {
          for (const weight of sorted)
            faces.push({
              ...base,
              weight: [weight, weight],
              file: `${slug}-${subset}-${weight}-${style}.woff2`,
            });
        }
      }
    }
  }
  return faces;
}

const formatWeight = ([min, max]: PlannedFontFace['weight']): string =>
  min === max ? `${min}` : `${min} ${max}`;

/** Render planned faces as CSS whose `src` urls are relative to `fontsDir`. */
export function renderFontFaces(
  faces: readonly PlannedFontFace[],
  fontsDir = './fonts',
): string {
  const header = `/* Webfonts — AUTO-GENERATED by @thijulio/core from fonts.config.mjs; do not
   edit. Self-hosted (no third-party requests): the woff2 files and their SIL
   OFL 1.1 licences ship in ${fontsDir}/, next to this bundle. */`;
  const rules = faces.map(
    (
      face,
    ) => `/* ${fontSlug(face.package)} ${face.style} ${formatWeight(face.weight)} ${face.subset} */
@font-face {
  font-family: '${face.family}';
  font-style: ${face.style};
  font-weight: ${formatWeight(face.weight)};
  font-display: swap;
  src: url('${fontsDir}/${face.file}') format('woff2');
  unicode-range: ${normalizeUnicodeRange(face.unicodeRange)};
}`,
  );
  return [header, ...rules].join('\n\n');
}

/** `U+0000-00FF,U+0131` and `U+0000-00FF, U+0131` compare equal. */
export const normalizeUnicodeRange = (range: string): string =>
  range
    .split(',')
    .map((part) => part.trim().toUpperCase())
    .filter(Boolean)
    .join(', ');

/** A parsed `@font-face` rule — what a browser would see. */
export interface ParsedFontFace {
  family: string;
  style: string;
  weight: readonly [min: number, max: number];
  display: string | undefined;
  srcUrls: string[];
  unicodeRange: string | undefined;
}

export const stripCssComments = (css: string): string =>
  css.replace(/\/\*[\s\S]*?\*\//g, '');

/** Parse every `@font-face` rule in a stylesheet. */
export function parseFontFaces(css: string): ParsedFontFace[] {
  return [...stripCssComments(css).matchAll(/@font-face\s*\{([^}]*)\}/g)].map(
    ([, body]) => {
      const prop = (name: string): string | undefined =>
        body
          .match(new RegExp(`(?:^|;)\\s*${name}\\s*:\\s*([^;]+)`))?.[1]
          ?.trim();
      const [min, max = min] = (prop('font-weight') ?? '400')
        .split(/\s+/)
        .map(Number);
      return {
        family: (prop('font-family') ?? '').replace(/^['"]|['"]$/g, ''),
        style: prop('font-style') ?? 'normal',
        weight: [min, max],
        display: prop('font-display'),
        srcUrls: [
          ...(prop('src') ?? '').matchAll(/url\(\s*(['"]?)(.*?)\1\s*\)/g),
        ].map((m) => m[2]),
        unicodeRange: prop('unicode-range'),
      };
    },
  );
}
