/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonVariant } from "./components/tj-button/tj-button";
export { ButtonVariant } from "./components/tj-button/tj-button";
export namespace Components {
    /**
     * Button — brand-agnostic action control. Same skin as the React primitive:
     * the shadow root loads
     * @thijulio /primitives' Button.module.css as plain CSS,
     * and every colour resolves through the inherited `--ds-*` contract.
     */
    interface TjButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Render a link when supplied; disabled links remain disabled buttons.
         */
        "href"?: string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Intent. primary = brand fill, accent = accent fill; the rest as named.
          * @default 'primary'
         */
        "variant": ButtonVariant;
    }
    /**
     * Input — text control with the shared Input skin (the shadow root loads
     * @thijulio /primitives' Input.module.css). Form-associated: it submits with a
     * light-DOM <form> and reports its value through ElementInternals.
     */
    interface TjInput {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Flip to the danger outline.
          * @default false
         */
        "invalid": boolean;
        "name"?: string;
        "placeholder"?: string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'text'
         */
        "type": 'text' | 'email' | 'search' | 'tel' | 'url' | 'password';
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface TjInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTjInputElement;
}
declare global {
    /**
     * Button — brand-agnostic action control. Same skin as the React primitive:
     * the shadow root loads
     * @thijulio /primitives' Button.module.css as plain CSS,
     * and every colour resolves through the inherited `--ds-*` contract.
     */
    interface HTMLTjButtonElement extends Components.TjButton, HTMLStencilElement {
    }
    var HTMLTjButtonElement: {
        prototype: HTMLTjButtonElement;
        new (): HTMLTjButtonElement;
    };
    interface HTMLTjInputElementEventMap {
        "tjInput": string;
        "tjChange": string;
    }
    /**
     * Input — text control with the shared Input skin (the shadow root loads
     * @thijulio /primitives' Input.module.css). Form-associated: it submits with a
     * light-DOM <form> and reports its value through ElementInternals.
     */
    interface HTMLTjInputElement extends Components.TjInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTjInputElementEventMap>(type: K, listener: (this: HTMLTjInputElement, ev: TjInputCustomEvent<HTMLTjInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTjInputElementEventMap>(type: K, listener: (this: HTMLTjInputElement, ev: TjInputCustomEvent<HTMLTjInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTjInputElement: {
        prototype: HTMLTjInputElement;
        new (): HTMLTjInputElement;
    };
    interface HTMLElementTagNameMap {
        "tj-button": HTMLTjButtonElement;
        "tj-input": HTMLTjInputElement;
    }
}
declare namespace LocalJSX {
    /**
     * Button — brand-agnostic action control. Same skin as the React primitive:
     * the shadow root loads
     * @thijulio /primitives' Button.module.css as plain CSS,
     * and every colour resolves through the inherited `--ds-*` contract.
     */
    interface TjButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * Render a link when supplied; disabled links remain disabled buttons.
         */
        "href"?: string;
        /**
          * The name of the element, used when submitting an HTML form.
         */
        "name"?: string;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Intent. primary = brand fill, accent = accent fill; the rest as named.
          * @default 'primary'
         */
        "variant"?: ButtonVariant;
    }
    /**
     * Input — text control with the shared Input skin (the shadow root loads
     * @thijulio /primitives' Input.module.css). Form-associated: it submits with a
     * light-DOM <form> and reports its value through ElementInternals.
     */
    interface TjInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * Flip to the danger outline.
          * @default false
         */
        "invalid"?: boolean;
        "name"?: string;
        /**
          * Fires when the value is committed (blur / enter), like native `change`.
         */
        "onTjChange"?: (event: TjInputCustomEvent<string>) => void;
        /**
          * Fires on every edit with the current value (v-model / ngModel hook).
         */
        "onTjInput"?: (event: TjInputCustomEvent<string>) => void;
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'text'
         */
        "type"?: 'text' | 'email' | 'search' | 'tel' | 'url' | 'password';
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface TjButtonAttributes {
        "variant": ButtonVariant;
        "size": 'sm' | 'md' | 'lg';
        "href": string;
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
    }
    interface TjInputAttributes {
        "value": string;
        "name": string;
        "placeholder": string;
        "type": 'text' | 'email' | 'search' | 'tel' | 'url' | 'password';
        "disabled": boolean;
        "required": boolean;
        "invalid": boolean;
    }

    interface IntrinsicElements {
        "tj-button": Omit<TjButton, keyof TjButtonAttributes> & { [K in keyof TjButton & keyof TjButtonAttributes]?: TjButton[K] } & { [K in keyof TjButton & keyof TjButtonAttributes as `attr:${K}`]?: TjButtonAttributes[K] } & { [K in keyof TjButton & keyof TjButtonAttributes as `prop:${K}`]?: TjButton[K] };
        "tj-input": Omit<TjInput, keyof TjInputAttributes> & { [K in keyof TjInput & keyof TjInputAttributes]?: TjInput[K] } & { [K in keyof TjInput & keyof TjInputAttributes as `attr:${K}`]?: TjInputAttributes[K] } & { [K in keyof TjInput & keyof TjInputAttributes as `prop:${K}`]?: TjInput[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Button — brand-agnostic action control. Same skin as the React primitive:
             * the shadow root loads
             * @thijulio /primitives' Button.module.css as plain CSS,
             * and every colour resolves through the inherited `--ds-*` contract.
             */
            "tj-button": LocalJSX.IntrinsicElements["tj-button"] & JSXBase.HTMLAttributes<HTMLTjButtonElement>;
            /**
             * Input — text control with the shared Input skin (the shadow root loads
             * @thijulio /primitives' Input.module.css). Form-associated: it submits with a
             * light-DOM <form> and reports its value through ElementInternals.
             */
            "tj-input": LocalJSX.IntrinsicElements["tj-input"] & JSXBase.HTMLAttributes<HTMLTjInputElement>;
        }
    }
}
